<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ApplyInfo.aspx.cs" Inherits="Teleware.ZPG.Client.Web.res.ApplyInfo" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>申请资料</title>
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <link href="../css/main.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div class="container">
        <div class="content" style="+zoom: 1;">
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            申请资料
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            申请宗地：
                        </td>
                        <td colspan="3">
                            公共标题公共标题公共标题公共标题公共标题
                        </td>
                    </tr>
                    <tr>
                        <td>
                            申请类型：
                        </td>
                        <td>
                            法人
                        </td>
                    </tr>
                    <tr>
                        <td>
                            申请时间：
                        </td>
                        <td>
                            2014-01-01
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            竞买人基本信息(自然人)
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件类型：
                        </td>
                        <td>
                            身份证
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件号码：
                        </td>
                        <td>
                            350823198604283713
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位：
                        </td>
                        <td>
                            特力惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            竞买人基本信息(法人、组织)
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 120px">
                            单位名称：
                        </td>
                        <td>
                            特立惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位注册代码：
                        </td>
                        <td>
                            007
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            竞买人基本信息(联合竞买人)
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件类型：
                        </td>
                        <td>
                            身份证
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件号码：
                        </td>
                        <td>
                            350823198604283713
                        </td>
                    </tr>
                    <tr>
                        <td>
                            职务：
                        </td>
                        <td>
                            .NET开发
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位：
                        </td>
                        <td>
                            特力惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            竞买人基本信息(联合竞买人（法人、组织）)
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件类型：
                        </td>
                        <td>
                            身份证
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件号码：
                        </td>
                        <td>
                            350823198604283713
                        </td>
                    </tr>
                    <tr>
                        <td>
                            职务：
                        </td>
                        <td>
                            .NET开发
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位：
                        </td>
                        <td>
                            特力惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位名称：
                        </td>
                        <td>
                            特立惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位注册代码：
                        </td>
                        <td>
                            007
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            法定代表人
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件类型：
                        </td>
                        <td>
                            身份证
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件号码：
                        </td>
                        <td>
                            350823198604283713
                        </td>
                    </tr>
                    <tr>
                        <td>
                            职务：
                        </td>
                        <td>
                            .NET开发
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            委托代理人
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件类型：
                        </td>
                        <td>
                            身份证
                        </td>
                    </tr>
                    <tr>
                        <td>
                            证件号码：
                        </td>
                        <td>
                            350823198604283713
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位：
                        </td>
                        <td>
                            特力惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-field" border="0" cellpadding="0" cellspacing="0" style="margin: 5px auto;">
                <thead>
                    <tr class="Header">
                        <td colspan="2">
                            联系人
                        </td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td style="width: 80px">
                            姓名：
                        </td>
                        <td>
                            刘标才
                        </td>
                    </tr>
                    <tr>
                        <td>
                            固定电话：
                        </td>
                        <td>
                            12345678
                        </td>
                    </tr>
                    <tr>
                        <td>
                            移动电话：
                        </td>
                        <td>
                            15980258754
                        </td>
                    </tr>
                    <tr>
                        <td>
                            电子邮箱
                        </td>
                        <td>
                            361883700@qq.com
                        </td>
                    </tr>
                    <tr>
                        <td>
                            单位：
                        </td>
                        <td>
                            特力惠电子有限公司
                        </td>
                    </tr>
                    <tr>
                        <td>
                            地址：
                        </td>
                        <td>
                            福建省福州市鼓楼区
                        </td>
                    </tr>
                    <tr>
                        <td>
                            邮编：
                        </td>
                        <td>
                            350001
                        </td>
                    </tr>
                </tbody>
            </table>
            <table class="table-grid" border="0" style="text-align: center" cellpadding="0" cellspacing="0"
                style="margin: 5px auto;">
                <tbody>
                    <tr class="Header">
                        <td colspan="3">
                            上传资料
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 150px; text-align: center;">
                            附件类型
                        </td>
                        <td style="text-align: center;">
                            附件名称
                        </td>
                        <td style="width: 80px; text-align: center;">
                            下载
                        </td>
                    </tr>
                    <tr>
                        <td>
                            附件1
                        </td>
                        <td>
                            附件1.doc
                        </td>
                        <td>
                            <a href="">下载</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            附件1
                        </td>
                        <td>
                            附件1.doc
                        </td>
                        <td>
                            <a href="">下载</a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    </form>
</body>
</html>
