//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlw.ZPG.Domain.Mapping
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using Tlw.ZPG.Domain.Models;
    
    internal partial class AccountVerifyMap : EntityTypeConfiguration<AccountVerify>
    {
        public AccountVerifyMap()
        {                        
              this.HasKey(t => t.VerifyId);        
              this.ToTable("A_AccountVerify");
              this.Property(t => t.VerifyId).HasColumnName("VerifyId");
              this.Property(t => t.AccountInfoId).HasColumnName("AccountInfoId");
              this.Property(t => t.CreateTime).HasColumnName("CreateTime");
              this.Property(t => t.VerifyAccountId).HasColumnName("VerifyAccountId");
              this.Property(t => t.VerifyAccount).HasColumnName("VerifyAccount").IsRequired().HasMaxLength(50);
              this.Property(t => t.Content).HasColumnName("Content").IsRequired().HasMaxLength(500);
              this.Property(t => t.IsBider).HasColumnName("IsBider");
         }
    }
}
