//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlw.ZPG.Domain.Mapping
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using Tlw.ZPG.Domain.Models;
    
    internal partial class CountyMap : EntityTypeConfiguration<County>
    {
        public CountyMap()
        {                        
              this.HasKey(t => t.ID);        
              this.ToTable("T_County");
              this.Property(t => t.ID).HasColumnName("CountyId");
              this.Property(t => t.CountyName).HasColumnName("CountyName").IsRequired().IsUnicode(false).HasMaxLength(20);
              this.Property(t => t.ParentId).HasColumnName("ParentId");
              this.Property(t => t.CountyCode).HasColumnName("CountyCode").HasMaxLength(50);
              this.Property(t => t.OrderNo).HasColumnName("OrderNo");
              this.Property(t => t.FullName).HasColumnName("FullName").HasMaxLength(100);
              
         }
    }
}
