//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlw.ZPG.Domain.Mapping
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using Tlw.ZPG.Domain.Models;
    
    internal partial class MenuMap : EntityTypeConfiguration<Menu>
    {
        public MenuMap()
        {                        
              this.HasKey(t => t.MenuId);        
              this.ToTable("U_Menu");
              this.Property(t => t.MenuId).HasColumnName("MenuId");
              this.Property(t => t.MenuName).HasColumnName("MenuName").IsRequired().HasMaxLength(50);
              this.Property(t => t.MenuUrl).HasColumnName("MenuUrl").HasMaxLength(200);
              this.Property(t => t.ParentId).HasColumnName("ParentId");
              this.Property(t => t.MenuIcon).HasColumnName("MenuIcon").HasMaxLength(200);
              this.Property(t => t.OrderNo).HasColumnName("OrderNo");
              this.Property(t => t.MenuCode).HasColumnName("MenuCode").HasMaxLength(50);
         }
    }
}
