//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlw.ZPG.Domain.Mapping
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using Tlw.ZPG.Domain.Models;
    
    internal partial class PersonMap : EntityTypeConfiguration<Person>
    {
        public PersonMap()
        {                        
              this.HasKey(t => t.PersonId);        
              this.ToTable("A_Person");
              this.Property(t => t.PersonId).HasColumnName("PersonId");
              this.Property(t => t.AccountInfoId).HasColumnName("AccountInfoId");
              this.Property(t => t.PersonName).HasColumnName("PersonName").HasMaxLength(50);
              this.Property(t => t.PassportType).HasColumnName("PassportType").HasMaxLength(50);
              this.Property(t => t.PassportNumber).HasColumnName("PassportNumber").HasMaxLength(100);
              this.Property(t => t.Unit).HasColumnName("Unit").HasMaxLength(100);
              this.Property(t => t.UnitCode).HasColumnName("UnitCode").HasMaxLength(50);
              this.Property(t => t.Address).HasColumnName("Address").HasMaxLength(200);
              this.Property(t => t.Telephone).HasColumnName("Telephone").HasMaxLength(50);
              this.Property(t => t.MobilePhone).HasColumnName("MobilePhone").HasMaxLength(50);
              this.Property(t => t.Email).HasColumnName("Email").HasMaxLength(50);
              this.Property(t => t.Business).HasColumnName("Business").HasMaxLength(50);
              this.Property(t => t.PostalCode).HasColumnName("PostalCode").HasMaxLength(50);
         }
    }
}
