//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tlw.ZPG.Domain.Mapping
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    using Tlw.ZPG.Domain.Models;
    
    internal partial class PurposeMap : EntityTypeConfiguration<Purpose>
    {
        public PurposeMap()
        {                        
              this.HasKey(t => t.PurposeId);        
              this.ToTable("Z_Purpose");
              this.Property(t => t.PurposeId).HasColumnName("PurposeId");
              this.Property(t => t.LandId).HasColumnName("LandId");
              this.Property(t => t.PurposeName).HasColumnName("PurposeName").IsRequired().HasMaxLength(100);
              this.Property(t => t.ParentId).HasColumnName("ParentId");
         }
    }
}
